# <center>PDL_LAB_03_A - Tensor operation using tf.keras</center>

#### import necessary module 

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
a = [1,2,3,4]

**Tensor Axes**

In [4]:
dd = [[1,2,3],[4,5,6],[7,8,9]]                       ## take 2d array 

### Each element along the first axis, is an array:

In [5]:
dd[0]                                            

[1, 2, 3]

In [6]:
dd[1]

[4, 5, 6]

In [7]:
dd[2]

[7, 8, 9]

### Each element along the second axis, is a number:

In [8]:
dd[0][0]

1

In [9]:
dd[0][1]

2

In [10]:
dd[0][2]

3

In [11]:
dd[1][0]

4

In [12]:
dd[1][1]

5

In [13]:
dd[1][2]

6

In [14]:
dd[2][0]

7

In [15]:
dd[2][1]

8

In [16]:
dd[2][2]

9

**Shape of Tensor**

shape of tensor gives length of each axis of tensor

In [17]:
t=tf.constant(dd)                  ## convert 2d array to a constant tensors of shape 3x3
t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [18]:
type(t)                                   #type of varibale t

tensorflow.python.framework.ops.EagerTensor

In [19]:
t.shape                                   #shape of tensor t

TensorShape([3, 3])

**Tensor Operation Types**

#### Reshaping A Tensor In TensorFlow

In [20]:
t = tf.constant([[1,1,1,1],[2,2,2,2],[3,3,3,3]],dtype=tf.float32)             
t                             #can reshape a tensor that product of new shape gives equal value 

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]], dtype=float32)>

In [21]:
t.shape

TensorShape([3, 4])

In [22]:
reshaped_tensor_t = tf.reshape(t,[1,12]) 
print(reshaped_tensor_t)                      

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


product of [3,4] is 12

product of [1,12] is 12

product of [4,3] is 12

product of [2,6] is 12

In [23]:
reshaped_tensor_t = tf.reshape(t,[2,6]) 
print(reshaped_tensor_t)

tf.Tensor(
[[1. 1. 1. 1. 2. 2.]
 [2. 2. 3. 3. 3. 3.]], shape=(2, 6), dtype=float32)


In [24]:
reshaped_tensor_t = tf.reshape(t,[4,3]) 
print(reshaped_tensor_t)

tf.Tensor(
[[1. 1. 1.]
 [1. 2. 2.]
 [2. 2. 3.]
 [3. 3. 3.]], shape=(4, 3), dtype=float32)


##### shaping in 3 dimension 

making the tensor of size 12 to a 3d tensor 

product of [2,2,3] is 12

In [25]:
reshaped_tensor_t = tf.reshape(t, [2,2,3])
print(reshaped_tensor_t)

tf.Tensor(
[[[1. 1. 1.]
  [1. 2. 2.]]

 [[2. 2. 3.]
  [3. 3. 3.]]], shape=(2, 2, 3), dtype=float32)


#### Changing Shape By Squeezing And Unsqueezing


Squeezing a tensor removes the dimensions or axes that have a length of one.

In [38]:
print(tf.reshape(t,[1,12]))

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [39]:
print(tf.reshape(t,[1,12]).shape)                              #shape of t is 1x12

(1, 12)


In [40]:
print(tf.squeeze(tf.reshape(t,[1,12])))                      #after applying squeeze to t gives single vector of (12,)   

tf.Tensor([1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.], shape=(12,), dtype=float32)


In [41]:
print(tf.squeeze(tf.reshape(t,[1,12])).shape)

(12,)


**Flatten A Tensor**

Flattening a tensor means to remove all of the dimensions except for one

In [42]:
def fatten(t):                                               #an user-define function reshape tensor and return in single vector
    t = tf.squeeze(tf.reshape(t,[1,-1]))
    return t

In [43]:
to = tf.ones([4,3])                      #creates tensor of shape 4x3 filled with 1's  
to

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [44]:
fatten(to)                                       #apply fatten function to above tensor 'to'

<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

**Concatenating Tensors**

concat() function resulting tensor will have shape depends on the two given input tensors

In [45]:
t1 = tf.constant([[1,2],[3,4]])                    
t2 = tf.constant([[5,6],[7,8]])                     #create two tensor of shape (2x2)

In [46]:
tc0=tf.concat((t1,t2),axis=0)
tc0                                                #concatenate two tensor on bases of axis = 0

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [47]:
tc1=tf.concat((t1,t2),axis=1)
tc1                                                  #concatenate two tensor on bases of axis = 1 

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

In [48]:
tc0.shape                        

TensorShape([4, 2])

In [49]:
tc1.shape

TensorShape([2, 4])