# <center>PDL_LAB_07_A-matrix_math & loss or cost function</center> 

In [1]:
import numpy as np
import math

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.3085,0.3098,0.9840,0.5783,0.7805])

Implement mean squared error (or MSE) in two ways,

1) Without using numpy (i.e. using plain python)

2) With the use of numpy


**without using numpy**

In [3]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [4]:
mae(y_predicted, y_true)

Total error is: 3.1635
Mean absolute error is: 0.6327


0.6327

**using numpy**

In [5]:
np.abs(y_true-y_predicted)

array([0.6915, 0.6902, 0.984 , 0.5783, 0.2195])

In [6]:
np.mean(np.abs(y_true-y_predicted))

0.6327

In [7]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_true-y_predicted))

In [8]:
mae_np(y_predicted, y_true)

0.6327

### Implement Log Loss or Binary Cross Entropy

In [9]:
np.log([0])

<ipython-input-9-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
epsilon = 1e-15

In [11]:
np.log([1e-15])

array([-34.53877639])

In [12]:
y_predicted

array([1, 1, 0, 0, 1])

In [13]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [14]:
1-epsilon

0.999999999999999

In [15]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [16]:
y_predicted_new = np.array(y_predicted_new)

In [17]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [18]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

21.852939888141037

In [19]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [20]:
log_loss(y_true, y_predicted)

21.852939888141037

<h3 style='color:purple'>Exercise</h3>

Implement mean squared error (or MSE) in two ways,

1) Without using numpy (i.e. using plain python)

2) With the use of numpy

**without using numpy**

In [21]:
def mse(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)**2
    print("Total error is:",total_error)
    mse = total_error/len(y_predicted)
    print("Mean square error is:",mse)
    return mse

In [22]:
mse(y_predicted, y_true)

Total error is: 2.30541543
Mean square error is: 0.46108308600000003


0.46108308600000003

**with the use of numpy**

In [23]:
np.abs(y_true-y_predicted)

array([0.6915, 0.6902, 0.984 , 0.5783, 0.2195])

In [24]:
np.square(np.abs(y_true-y_predicted))

array([0.47817225, 0.47637604, 0.968256  , 0.33443089, 0.04818025])

In [25]:
np.sum(np.square(np.abs(y_true-y_predicted)))

2.30541543

In [26]:
np.sum(np.square(np.abs(y_true-y_predicted)))/len(y_true)

0.46108308600000003

In [27]:
def mse_np(y_predicted,y_true):
    return np.mean(np.square(np.abs(y_true-y_predicted)))

In [28]:
mse_np(y_predicted,y_true)

0.46108308600000003

### Calculate profit/loss from revenue and expenses

In [29]:
revenue = np.array([[300,485,953],
                    [28,79,48],
                    [69,83,75]])           #3x3
expenses = np.array([[250,198,480],
                     [17,50,10],
                     [48,59,61]])          #3x3

In [30]:
profit = revenue - expenses
profit

array([[ 50, 287, 473],
       [ 11,  29,  38],
       [ 21,  24,  14]])

### Calculate total sales from units and price per unit using matrix multiplication

In [31]:
price_per_unit = np.array([1900,3000,2500])                 #3x1
units = np.array([[55,68,72],
                  [7,14,21],
                  [3,16,9]])  

In [32]:
price_per_unit*units     

array([[104500, 204000, 180000],
       [ 13300,  42000,  52500],
       [  5700,  48000,  22500]])

In above case numpy is using broadcasting so it expands price_per_unit array from 1 row, 3 columns to 3 row and 3 columns. Correct way to do matrix multiplication is to use dot product as shown below

In [33]:
np.dot(price_per_unit,units)       

array([133000, 211200, 222300])

[Solution](https://github.com/codebasics/deep-learning-keras-tf-tutorial/blob/main/5_loss/loss_function_exercise_solution.ipynb)