## <center>LAB 4: Designing Logic Gates Using Keras</center>

### Arzoo Sah
### 205229103

**Import the necessary module**

In [1]:
import numpy as np
from keras.models import Sequential 
from keras.layers import Dense 
from sklearn.metrics import accuracy_score

**Take input layers of size 4 with 2 dimension**

In [2]:
train = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')

**Take Output layers of all Gates with size 4** 

In [3]:
test_or = np.array([[0],[1],[1],[1]],'float32')
test_and = np.array([[0],[0],[0],[1]],'float32')
test_nor = np.array([[1],[0],[0],[0]],'float32')
test_nand = np.array([[1],[1],[1],[0]],'float32')
test_xor = np.array([[0],[1],[1],[0]],'float32')

**Declare the model with specific parameter**

In [4]:
model = Sequential()
model.add(Dense(16,input_dim=2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['binary_accuracy'])

**OR GATE**

In [5]:
model.fit(train,test_or,epochs=100,verbose=2)              #fit the model for OR Gate 

Epoch 1/100
1/1 - 1s - loss: 0.2324 - binary_accuracy: 1.0000
Epoch 2/100
1/1 - 0s - loss: 0.2307 - binary_accuracy: 0.7500
Epoch 3/100
1/1 - 0s - loss: 0.2289 - binary_accuracy: 0.7500
Epoch 4/100
1/1 - 0s - loss: 0.2272 - binary_accuracy: 0.7500
Epoch 5/100
1/1 - 0s - loss: 0.2255 - binary_accuracy: 0.7500
Epoch 6/100
1/1 - 0s - loss: 0.2238 - binary_accuracy: 0.7500
Epoch 7/100
1/1 - 0s - loss: 0.2222 - binary_accuracy: 0.7500
Epoch 8/100
1/1 - 0s - loss: 0.2205 - binary_accuracy: 0.7500
Epoch 9/100
1/1 - 0s - loss: 0.2189 - binary_accuracy: 0.7500
Epoch 10/100
1/1 - 0s - loss: 0.2173 - binary_accuracy: 0.7500
Epoch 11/100
1/1 - 0s - loss: 0.2157 - binary_accuracy: 0.7500
Epoch 12/100
1/1 - 0s - loss: 0.2141 - binary_accuracy: 0.7500
Epoch 13/100
1/1 - 0s - loss: 0.2125 - binary_accuracy: 0.7500
Epoch 14/100
1/1 - 0s - loss: 0.2110 - binary_accuracy: 0.7500
Epoch 15/100
1/1 - 0s - loss: 0.2094 - binary_accuracy: 0.7500
Epoch 16/100
1/1 - 0s - loss: 0.2079 - binary_accuracy: 0.7500
E

In [6]:
model.predict(train).round()                          #predict the model 

array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [7]:
accuracy_score(test_or,model.predict(train).round())       #accuracy of OR Gate 

0.75

**AND GATE**

In [8]:
model.fit(train,test_and,epochs=100,verbose=2)             #fit the model for AND Gate

Epoch 1/100
1/1 - 0s - loss: 0.3163 - binary_accuracy: 0.2500
Epoch 2/100
1/1 - 0s - loss: 0.3165 - binary_accuracy: 0.2500
Epoch 3/100
1/1 - 0s - loss: 0.3165 - binary_accuracy: 0.2500
Epoch 4/100
1/1 - 0s - loss: 0.3162 - binary_accuracy: 0.2500
Epoch 5/100
1/1 - 0s - loss: 0.3157 - binary_accuracy: 0.2500
Epoch 6/100
1/1 - 0s - loss: 0.3151 - binary_accuracy: 0.2500
Epoch 7/100
1/1 - 0s - loss: 0.3144 - binary_accuracy: 0.2500
Epoch 8/100
1/1 - 0s - loss: 0.3136 - binary_accuracy: 0.2500
Epoch 9/100
1/1 - 0s - loss: 0.3127 - binary_accuracy: 0.2500
Epoch 10/100
1/1 - 0s - loss: 0.3117 - binary_accuracy: 0.2500
Epoch 11/100
1/1 - 0s - loss: 0.3107 - binary_accuracy: 0.2500
Epoch 12/100
1/1 - 0s - loss: 0.3096 - binary_accuracy: 0.2500
Epoch 13/100
1/1 - 0s - loss: 0.3085 - binary_accuracy: 0.2500
Epoch 14/100
1/1 - 0s - loss: 0.3073 - binary_accuracy: 0.2500
Epoch 15/100
1/1 - 0s - loss: 0.3060 - binary_accuracy: 0.2500
Epoch 16/100
1/1 - 0s - loss: 0.3048 - binary_accuracy: 0.2500
E

In [9]:
model.predict(train).round()                                #predict the model 

array([[0.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [10]:
accuracy_score(test_and,model.predict(train).round())                  #accuracy of AND Gate 

0.5

**NOR GATE**

In [11]:
model.fit(train,test_nor,epochs=100,verbose=2)            #fit the model for NOR Gate

Epoch 1/100
1/1 - 0s - loss: 0.3077 - binary_accuracy: 0.0000e+00
Epoch 2/100
1/1 - 0s - loss: 0.3064 - binary_accuracy: 0.0000e+00
Epoch 3/100
1/1 - 0s - loss: 0.3047 - binary_accuracy: 0.0000e+00
Epoch 4/100
1/1 - 0s - loss: 0.3029 - binary_accuracy: 0.0000e+00
Epoch 5/100
1/1 - 0s - loss: 0.3008 - binary_accuracy: 0.0000e+00
Epoch 6/100
1/1 - 0s - loss: 0.2986 - binary_accuracy: 0.0000e+00
Epoch 7/100
1/1 - 0s - loss: 0.2962 - binary_accuracy: 0.2500
Epoch 8/100
1/1 - 0s - loss: 0.2936 - binary_accuracy: 0.2500
Epoch 9/100
1/1 - 0s - loss: 0.2910 - binary_accuracy: 0.2500
Epoch 10/100
1/1 - 0s - loss: 0.2883 - binary_accuracy: 0.5000
Epoch 11/100
1/1 - 0s - loss: 0.2856 - binary_accuracy: 0.5000
Epoch 12/100
1/1 - 0s - loss: 0.2827 - binary_accuracy: 0.5000
Epoch 13/100
1/1 - 0s - loss: 0.2799 - binary_accuracy: 0.5000
Epoch 14/100
1/1 - 0s - loss: 0.2771 - binary_accuracy: 0.5000
Epoch 15/100
1/1 - 0s - loss: 0.2742 - binary_accuracy: 0.5000
Epoch 16/100
1/1 - 0s - loss: 0.2714 - b

In [12]:
model.predict(train).round()                              #predict the model 

array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [13]:
accuracy_score(test_nor,model.predict(train).round())                     #accuracy of NOR Gate 

0.75

**NAND GATE**

In [14]:
model.fit(train,test_nand,epochs=100,verbose=2)               #fit the model for NAND Gate

Epoch 1/100
1/1 - 0s - loss: 0.3454 - binary_accuracy: 0.2500
Epoch 2/100
1/1 - 0s - loss: 0.3459 - binary_accuracy: 0.2500
Epoch 3/100
1/1 - 0s - loss: 0.3460 - binary_accuracy: 0.2500
Epoch 4/100
1/1 - 0s - loss: 0.3459 - binary_accuracy: 0.2500
Epoch 5/100
1/1 - 0s - loss: 0.3456 - binary_accuracy: 0.2500
Epoch 6/100
1/1 - 0s - loss: 0.3450 - binary_accuracy: 0.2500
Epoch 7/100
1/1 - 0s - loss: 0.3443 - binary_accuracy: 0.2500
Epoch 8/100
1/1 - 0s - loss: 0.3434 - binary_accuracy: 0.2500
Epoch 9/100
1/1 - 0s - loss: 0.3424 - binary_accuracy: 0.2500
Epoch 10/100
1/1 - 0s - loss: 0.3413 - binary_accuracy: 0.2500
Epoch 11/100
1/1 - 0s - loss: 0.3401 - binary_accuracy: 0.2500
Epoch 12/100
1/1 - 0s - loss: 0.3388 - binary_accuracy: 0.2500
Epoch 13/100
1/1 - 0s - loss: 0.3374 - binary_accuracy: 0.2500
Epoch 14/100
1/1 - 0s - loss: 0.3360 - binary_accuracy: 0.2500
Epoch 15/100
1/1 - 0s - loss: 0.3345 - binary_accuracy: 0.2500
Epoch 16/100
1/1 - 0s - loss: 0.3330 - binary_accuracy: 0.2500
E

In [15]:
model.predict(train).round()                                 #predict the model 

array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [16]:
accuracy_score(test_nand,model.predict(train).round())                    #accuracy of NAND Gate 

0.25

**XOR GATE**

In [17]:
model.fit(train,test_xor,epochs=100,verbose=2)                 #fit the model for XOR Gate

Epoch 1/100
1/1 - 0s - loss: 0.2520 - binary_accuracy: 0.5000
Epoch 2/100
1/1 - 0s - loss: 0.2516 - binary_accuracy: 0.5000
Epoch 3/100
1/1 - 0s - loss: 0.2512 - binary_accuracy: 0.5000
Epoch 4/100
1/1 - 0s - loss: 0.2508 - binary_accuracy: 0.5000
Epoch 5/100
1/1 - 0s - loss: 0.2504 - binary_accuracy: 0.5000
Epoch 6/100
1/1 - 0s - loss: 0.2500 - binary_accuracy: 0.5000
Epoch 7/100
1/1 - 0s - loss: 0.2496 - binary_accuracy: 0.5000
Epoch 8/100
1/1 - 0s - loss: 0.2492 - binary_accuracy: 0.5000
Epoch 9/100
1/1 - 0s - loss: 0.2488 - binary_accuracy: 0.5000
Epoch 10/100
1/1 - 0s - loss: 0.2484 - binary_accuracy: 0.5000
Epoch 11/100
1/1 - 0s - loss: 0.2480 - binary_accuracy: 0.2500
Epoch 12/100
1/1 - 0s - loss: 0.2476 - binary_accuracy: 0.2500
Epoch 13/100
1/1 - 0s - loss: 0.2473 - binary_accuracy: 0.2500
Epoch 14/100
1/1 - 0s - loss: 0.2469 - binary_accuracy: 0.2500
Epoch 15/100
1/1 - 0s - loss: 0.2465 - binary_accuracy: 0.2500
Epoch 16/100
1/1 - 0s - loss: 0.2461 - binary_accuracy: 0.2500
E

In [18]:
model.predict(train).round()                           #predict the model 

array([[1.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [19]:
accuracy_score(test_xor,model.predict(train).round())                     #accuracy of XOR Gate 

0.75

**NOT GATE**

#### NOT Logic Gate requires input layers of size 2 with 2 dimension

In [20]:
train_not = np.array([[0],[1]],'float32')
test_not = np.array([[1],[0]],'float32')

In [21]:
model1 = Sequential()
model1.add(Dense(16,input_dim=1,activation='relu'))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='mean_squared_error',optimizer='adam',metrics=['binary_accuracy'])

In [22]:
model1.fit(train_not,test_not,epochs=100,verbose=2)                  #fit the model for NOT Gate

Epoch 1/100
1/1 - 0s - loss: 0.3368 - binary_accuracy: 0.0000e+00
Epoch 2/100
1/1 - 0s - loss: 0.3358 - binary_accuracy: 0.0000e+00
Epoch 3/100
1/1 - 0s - loss: 0.3347 - binary_accuracy: 0.0000e+00
Epoch 4/100
1/1 - 0s - loss: 0.3337 - binary_accuracy: 0.0000e+00
Epoch 5/100
1/1 - 0s - loss: 0.3326 - binary_accuracy: 0.0000e+00
Epoch 6/100
1/1 - 0s - loss: 0.3316 - binary_accuracy: 0.0000e+00
Epoch 7/100
1/1 - 0s - loss: 0.3306 - binary_accuracy: 0.0000e+00
Epoch 8/100
1/1 - 0s - loss: 0.3296 - binary_accuracy: 0.0000e+00
Epoch 9/100
1/1 - 0s - loss: 0.3286 - binary_accuracy: 0.0000e+00
Epoch 10/100
1/1 - 0s - loss: 0.3276 - binary_accuracy: 0.0000e+00
Epoch 11/100
1/1 - 0s - loss: 0.3266 - binary_accuracy: 0.0000e+00
Epoch 12/100
1/1 - 0s - loss: 0.3255 - binary_accuracy: 0.0000e+00
Epoch 13/100
1/1 - 0s - loss: 0.3246 - binary_accuracy: 0.0000e+00
Epoch 14/100
1/1 - 0s - loss: 0.3236 - binary_accuracy: 0.0000e+00
Epoch 15/100
1/1 - 0s - loss: 0.3226 - binary_accuracy: 0.0000e+00
Epoc

In [23]:
model1.predict(train_not).round()                                      #predict the model 

array([[0.],
       [0.]], dtype=float32)

In [24]:
accuracy_score(test_not,model1.predict(train_not).round())                 #accuracy of NOT Gate 

0.5