# <center>PDL_LAB_03_B-tensor operation using tf.keras</center>

In [ ]:
import tensorflow as tf
import numpy as np 

**Scalar-0 Rank Tensor**

In [ ]:
rank_0_tensor = tf.constant(4)                   # rank 0 of scalar contains single value  
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


**Vector-1 Rank Tensor**

In [ ]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])        #rank 1 of vectors contains list of values 
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


**Matrix-2 Rank Tensor**

In [ ]:
rank_2_tensor = tf.constant([[1, 2],[3, 4],[5, 6]], dtype=tf.float16)        #rank 2 of matrix with 2-axes 
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


**Tensor - 3 Rank** 

matrix with more than 2 axes is tensor 

In [ ]:
rank_3_tensor = tf.constant([[[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]],[[10, 11, 12, 13, 14],[15, 16, 17, 18, 19]],[[20, 21, 22, 23, 24],[25, 26, 27, 28, 29]],])
print(rank_3_tensor)                                            #rank 3 of tensor with 3-axes                             

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
np.array(rank_2_tensor)                #convert to numpy array 

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

**Maths on Tensors**

In [ ]:
a = tf.constant([[1, 2],[3, 4]])
b = tf.constant([[1, 1],[1, 1]])
print(tf.add(a, b), "\n")                              #adding both tensors 
print(tf.multiply(a, b), "\n")                         #element wise multiplication
print(tf.matmul(a, b), "\n")                           #matrix multiplication with tensors

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [ ]:
print(a + b, "\n")                                                #do mathematical operation without apply tensors 
print(a * b, "\n")                                                    
print(a @ b, "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



**Shape**

In [ ]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])                           #a tensor of 4d 

In [ ]:
print("Type of every element:", rank_4_tensor.dtype)           #details of the tensor of rank-4
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


**Indexing**

In [ ]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])         #tensor of rank-1

print(rank_1_tensor.numpy())                        #to convert in numpy 

[ 0  1  1  2  3  5  8 13 21 34]


In [ ]:
print("First:", rank_1_tensor[0].numpy())                             #gives element of 1d tensor 
print("Second:", rank_1_tensor[1].numpy())
print("Third:", rank_1_tensor[2].numpy())
print("Second Last:", rank_1_tensor[-2].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Third: 1
Second Last: 21
Last: 34


In [ ]:
print("Everything:", rank_1_tensor[:].numpy())           # to print enitre tensor
print("Before 4:", rank_1_tensor[:4].numpy())            # to print upto 4th position
print("From 4 to the end:", rank_1_tensor[4:].numpy())   # to print from 5th position to end 
print("From 2, before 7:", rank_1_tensor[2:7].numpy())   # to print from 2nd postion to 7th position
print("Every other item:", rank_1_tensor[::2].numpy())   # to print element of tensor with +2 increment
print("Reversed:", rank_1_tensor[::-1].numpy())          # to print element of tensor from reverse with -1 decrement

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


**Multi-axis indexing**

In [ ]:
print(rank_2_tensor.numpy())                    #calling element by multi-axis indexing

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
print(rank_2_tensor[1, 1].numpy())

4.0


In [ ]:
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [ ]:
print(rank_3_tensor[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


**Manipulating Shapes**

In [ ]:
var_x = tf.Variable(tf.constant([[1], [2], [3]]))             #tensor with shape 3x1
print(var_x.shape)

(3, 1)


In [ ]:
print(var_x.shape.as_list())         #converting numpy to list 

[3, 1]


In [ ]:
reshaped = tf.reshape(var_x, [1, 3])              #reshape to shape 1x3 (a transpose)

In [ ]:
print(var_x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [ ]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
print(tf.reshape(rank_3_tensor, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [ ]:
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3,(-2+1)]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


In [ ]:
print(tf.reshape(rank_3_tensor, [2, 3, 5]), "\n")

print(tf.reshape(rank_3_tensor, [5, 6]), "\n")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 



In [ ]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# Now, cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)
